export const USER_REPOSITORY = "USER_REPOSITORY";

export const TEMPLATE_REPOSITORY = "TEMPLATE_REPOSITORY";

export const ORDER_REPOSITORY = "ORDER_REPOSITORY";
export const TEMPLATE_STYLE_REPOSITORY =
  "TEMPLATE_STYLE_REPOSITORY";